% Copyright (C) 2022 Frank E. Curtis, Daniel P. Robinson, Qi Wang
%
% All Rights Reserved.

% SubproblemSolverMoreSorensen: printIterationValues
function printIterationValues(S,quantities,reporter)

% Print iteration values
reporter.printf(Enumerations.R_SOLVER,Enumerations.R_PER_ITERATION,...
  ' %e %e %e %d %e %e',...
  quantities.trustRegionRadius,...
  quantities.trustRegionMultiplier,...
  quantities.cubicMultiplier,...
  quantities.subproblemStatus,...
  norm(quantities.subproblemStep),...
  quantities.subproblemError);

end % printIterationValues