% Copyright (C) 2022 Frank E. Curtis, Daniel P. Robinson, Qi Wang
%
% All Rights Reserved.

% TRACE: printFooter
function printFooter(T)

% Print termination message
switch T.status_
  case Enumerations.S_UNSET
    T.reporter_.printf(Enumerations.R_SOLVER,Enumerations.R_BASIC,...
      '\nEXIT: Status unset!\n\n');
  case Enumerations.S_SUCCESS
    T.reporter_.printf(Enumerations.R_SOLVER,Enumerations.R_BASIC,...
      '\nEXIT: Stationary point found.\n\n');
  case Enumerations.S_CPU_TIME_LIMIT
    T.reporter_.printf(Enumerations.R_SOLVER,Enumerations.R_BASIC,...
      '\nEXIT: CPU time limit exceeded.\n\n');
  case Enumerations.S_SIZE_LIMIT
    T.reporter_.printf(Enumerations.R_SOLVER,Enumerations.R_BASIC,...
      '\nEXIT: Size limit exceeded.\n\n');
  case Enumerations.S_ITERATION_LIMIT
    T.reporter_.printf(Enumerations.R_SOLVER,Enumerations.R_BASIC,...
      '\nEXIT: Iteration limit exceeded.\n\n');
  case Enumerations.S_EVALUATION_LIMIT
    T.reporter_.printf(Enumerations.R_SOLVER,Enumerations.R_BASIC,...
      '\nEXIT: Evaluation limit exceeded.\n\n');
  case Enumerations.S_DIRECTION_COMPUTATION_FAILURE
    T.reporter_.printf(Enumerations.R_SOLVER,Enumerations.R_BASIC,...
      '\nEXIT: Direction computation failure.\n\n');
  otherwise
    T.reporter_.printf(Enumerations.R_SOLVER,Enumerations.R_BASIC,...
      '\nEXIT: Status unknown!\n\n');
end % switch

% Print quantities footer
T.reporter_.printf(Enumerations.R_SOLVER,Enumerations.R_BASIC,...
  ['Objective......................... : %+e\n'...
  'Objective (unscaled).............. : %+e\n'...
  'Stationarity error................ : %+e\n'...
  'Iterations........................ : %d\n'...
  'Objective function evaluations.... : %d\n'...
  'Objective gradient evaluations.... : %d\n'...
  'Objective Hessian evaluations..... : %d\n'...
  'CPU seconds....................... : %d\n'],...
  T.quantities_.currentIterate.objectiveFunction(T.quantities_),...
  T.quantities_.currentIterate.objectiveFunctionUnscaled(T.quantities_),...
  T.quantities_.currentIterate.stationarityError(T.quantities_),...
  T.quantities_.iterationCounter,...
  T.quantities_.objectiveFunctionEvaluationCounter,...
  T.quantities_.objectiveGradientEvaluationCounter,...
  T.quantities_.objectiveHessianEvaluationCounter,...
  T.quantities_.CPUTime);

end % printFooter