% Copyright (C) 2022 Frank E. Curtis, Daniel P. Robinson, Qi Wang
%
% All Rights Reserved.

% TRACE: printHeader
function printHeader(T,P)

% Print software name
T.reporter_.printf(Enumerations.R_SOLVER,Enumerations.R_BASIC,...
  ['+---------------------------------------------------------------------+\n'...
  '|                  TRACE                 |\n'...
  '| Open source code under the MIT License |\n'...
  '+----------------------------------------+\n'...
  '\n'...
  'This is TRACE version 0.1.0\n'...
  '\n']);

% Print problem information
T.reporter_.printf(Enumerations.R_SOLVER,Enumerations.R_BASIC,...
  ['Problem name...................... : %s\n'...
  'Number of variables............... : %d\n'...
  '\n'],...
  P.name,...
  P.numberOfVariables);

% Print header information
T.reporter_.printf(Enumerations.R_SOLVER,Enumerations.R_BASIC,...
  ['Direction computation............. : %s\n'...
  '\n'],...
  T.strategies_.directionComputation.name);

end % printHeader